In [7]:
import numpy as np

a = np.array([5, 4, 3, 1, 2])
a

array([5, 4, 3, 1, 2])

In [5]:
np.where(a>3)

(array([3], dtype=int64),)

In [8]:
np.argmax(a)

0

In [10]:
a = np.array([[5, 4, 3, 1],[9,88,6,45],[9,76,3,4]])
np.argmax(a, axis=1) # row 열이 가장 나중 axis가 됨

array([0, 1, 1], dtype=int64)

In [11]:
np.argmax(a, axis=0) # column

array([1, 1, 1, 1], dtype=int64)

In [14]:
def l1_norm(x):
    x_norm = np.abs(x) #리스트형
    x_norm = np.sum(x_norm) #다이나믹 타입으로 int형으로 변환
    return x_norm

x=[1,2]
l1_norm(x)

3

In [18]:
def l2_norm(x):
    x_norm = x*x #리스트형
    x_norm = np.sum(x_norm)
    x_norm = np.sqrt(x_norm)
    return x_norm

x=np.array([1,2]) # 일반리스트는 리스트끼리 곱이 안되므로 numpy를 이용해야함
print(x*x)
l2_norm(x)

[1 4]


2.23606797749979