In [7]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [8]:
xy = np.loadtxt('data/data-01-test-score.csv',delimiter=',',dtype=np.float32)

In [9]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
print(x_data, y_data)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [10]:
torch.manual_seed(1)

In [11]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [12]:
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

model =MultivariateLinearRegressionModel()

optimizer = optim.SGD(model.parameters(), lr= 1e-5)

nb_epochs =20
for epoch in range(nb_epochs+1):

    prediction = model(x_train)

    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 28693.490234
Epoch    1/20 Cost: 10618.750000
Epoch    2/20 Cost: 3936.015381
Epoch    3/20 Cost: 1465.219360
Epoch    4/20 Cost: 551.693909
Epoch    5/20 Cost: 213.934662
Epoch    6/20 Cost: 89.052254
Epoch    7/20 Cost: 42.876022
Epoch    8/20 Cost: 25.799620
Epoch    9/20 Cost: 19.482409
Epoch   10/20 Cost: 17.143106
Epoch   11/20 Cost: 16.274515
Epoch   12/20 Cost: 15.949698
Epoch   13/20 Cost: 15.825971
Epoch   14/20 Cost: 15.776586
Epoch   15/20 Cost: 15.754648
Epoch   16/20 Cost: 15.742906
Epoch   17/20 Cost: 15.734898
Epoch   18/20 Cost: 15.728318
Epoch   19/20 Cost: 15.722224
Epoch   20/20 Cost: 15.716328
