In [1]:
import tensorflow as tf
tf.__version__

'2.8.2'

In [2]:
layers = tf.keras.layers

### RNN 테스트를 위한 더미데이터 생성

In [3]:
inputs = tf.random.normal([2, 5, 4])

In [4]:
inputs

<tf.Tensor: shape=(2, 5, 4), dtype=float32, numpy=
array([[[-0.11093149,  0.6416794 , -0.7616502 ,  0.4101029 ],
        [ 0.15528187,  0.0366326 ,  0.39938986, -1.0147554 ],
        [-1.1766475 , -1.6606932 ,  0.05159168,  1.8574638 ],
        [-1.0371155 , -1.8715706 , -0.34450004, -0.8500877 ],
        [ 2.3941176 ,  1.3503282 , -0.65592086,  0.4968267 ]],

       [[-0.6215906 ,  0.5408317 , -1.0684992 ,  1.5572811 ],
        [ 1.2980417 ,  0.6553338 ,  0.32034212,  1.6587447 ],
        [-0.59841675, -0.14297657,  1.5393621 ,  0.23547451],
        [ 0.8145484 ,  0.49044836, -0.65111697, -0.42730376],
        [ 2.1965406 , -0.84141886, -2.1728978 , -0.40316632]]],
      dtype=float32)>

* tf.keras를 이용한 다양한 RNN layer를 구현해보자

## Multi-Layer RNN

![multilayer_rnn](https://user-images.githubusercontent.com/11681225/46912330-5fe5fd00-cfad-11e8-95c2-94bb8e7b1bf6.png)

In [20]:
model = tf.keras.Sequential()

In [21]:
model.add(layers.GRU(1, return_sequences=True)) # 2, 5, 4 -> 2, 5, 1
model.add(layers.GRU(1, return_sequences=True)) # 2, 1
model.add(layers.GRU(1, return_sequences=False)) # 2, 1을 입력값을 받을 수 없다.

In [22]:
model(inputs)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.09367895],
       [0.13066578]], dtype=float32)>

In [23]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru_9 (GRU)                 (2, 5, 1)                 21        
                                                                 
 gru_10 (GRU)                (2, 5, 1)                 12        
                                                                 
 gru_11 (GRU)                (2, 1)                    12        
                                                                 
Total params: 45
Trainable params: 45
Non-trainable params: 0
_________________________________________________________________


## Bi-directional RNN

![bidirectional_rnn](https://user-images.githubusercontent.com/11681225/46912324-3d53e400-cfad-11e8-8b09-85d8ebdb0e66.png)

In [9]:
model = tf.keras.Sequential()

In [10]:
model.add(layers.Bidirectional(layers.LSTM(1, return_sequences=True)))
model.add(layers.Bidirectional(layers.LSTM(1, return_sequences=True)))
model.add(layers.Bidirectional(layers.LSTM(1)))

In [11]:
model(inputs)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.00486168,  0.00312328],
       [-0.0467658 , -0.0357119 ]], dtype=float32)>

In [12]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bidirectional (Bidirectiona  (2, 5, 2)                48        
 l)                                                              
                                                                 
 bidirectional_1 (Bidirectio  (2, 5, 2)                32        
 nal)                                                            
                                                                 
 bidirectional_2 (Bidirectio  (2, 2)                   32        
 nal)                                                            
                                                                 
Total params: 112
Trainable params: 112
Non-trainable params: 0
_________________________________________________________________
