## Numpy Ex
### Numpy import
* 넘파이 사용을 위해 import
* 만약 설치가 안되어 있다면 설치해줍니다.
```
!pip install numpy
```


In [41]:
import numpy as np

## 문제 1: 배열 생성과 기본 연산
### 1.1 크기가 10인 0으로 채워진 배열 생성

In [2]:
# np.zeros
arr1 = np.zeros(8)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0.])

---

### 1.2 배열의 5번째 원소를 1로 설정

In [3]:
# indexing
arr1[4] = 1
arr1

array([0., 0., 0., 0., 1., 0., 0., 0.])

---

### 1.3 10에서 50까지의 정수를 담은 배열 생성

In [4]:
# np.arange
arr2 = np.arange(10,51)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

---

### 1.4 배열 뒤집기

In [5]:
# slicing
arr2_reversed = arr2[::-1]
arr2_reversed

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

---

### 1.5 3x3 단위행렬 생성

In [6]:
# np.eye
idt_mat = np.eye(3)
idt_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

---

## 문제 2: 통계

### 2.1 크기가 30인 무작위 정수 배열 생성, 평균 구하기

In [15]:
# randint
from numpy.random import randint
rand_arr = randint(0, 100, 30)
ave = np.mean(rand_arr)
print(rand_arr)
print(ave)

[83 44 70  4 36 41 67 51 11 55 84 29 26  0 32 21 71 84 58 12  7 51  9 70
 32 64 91 46 16 27]
43.06666666666667


---

### 2.2 5x5 크기의 2차원 배열, 최댓값과 최솟값 찾기

In [18]:
# rand(randint), np.max, np.min

rand_arr_2d = randint(low = 0, high= 30, size = (5, 5))
print(rand_arr_2d)
max_val, min_val = np.max(rand_arr_2d), np.min(rand_arr_2d)
print(max_val, min_val)

[[ 1  4 25 10  0]
 [13 28 23 11 27]
 [16 11 26  5 26]
 [ 2  2  3 12 16]
 [27 14 16 10  0]]
28 0


---

## 문제 3: 인덱싱과 슬라이싱

### 3.1 크기가 10인 배열 생성, 4번째에서 8번째 원소를 -1로 설정

In [19]:
# np.ones
arr3 = np.ones(10)
print(arr3)
arr3[3:8] = -1
print(arr3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1.  1.  1. -1. -1. -1. -1. -1.  1.  1.]


---

### 3.2 10x10 크기의 2차원 배열, 안쪽 8x8 추출

In [20]:
arr4 =randint(0, 100, (10, 10))
print(arr4)

inner_arr4 = arr4[1:9, 1:9]
print(inner_arr4)

[[15 25 49  9  0 48 26 32  9 64]
 [21 19 16 30 13  5  4 45 27 17]
 [30  1 80 15 97 56 68 57 62 10]
 [81 40  9 81 14 22 88 21 91 45]
 [95 55 84 13 86 22 30 17 12 42]
 [16 20 10  5 48 34 59 23 61 35]
 [61 88 55 75 70 50 96 91 92 16]
 [26 28 44 27 69 98 28 73 37 83]
 [21 62 10 77  9 93  1 91 56 92]
 [57 62 12 79 90 39 15 32 68 48]]
[[19 16 30 13  5  4 45 27]
 [ 1 80 15 97 56 68 57 62]
 [40  9 81 14 22 88 21 91]
 [55 84 13 86 22 30 17 12]
 [20 10  5 48 34 59 23 61]
 [88 55 75 70 50 96 91 92]
 [28 44 27 69 98 28 73 37]
 [62 10 77  9 93  1 91 56]]


---

## 문제 4: 불리언 인덱싱
### 4.1 크기가 10인 무작위 정수 배열 생성

In [25]:
# np.random.randint
rand_arr =randint(1,100,10)
print(rand_arr)

[32  9 53  3 49 71 79 59 90 63]


---

### 4.2 배열에서 8보다 큰 값만 추출

In [26]:
# 주어진 배열 안에서 arr[arr > 8] 조건에 만족하는 값을 뽑아서 출력해줍니다.

In [27]:
ft_rand_arr = rand_arr[rand_arr > 8]
print(ft_rand_arr)

[32  9 53 49 71 79 59 90 63]


---

## 문제 5: 선형대수
### 5.1 5x5 크기의 무작위 정수 배열 생성

In [29]:
# ran
mat = np.random.randint(0, 100, (5, 5))
print(mat)

[[92 87 89 93 27]
 [83 57 83  9 36]
 [ 3 84 37 42 55]
 [58 96  1 54 45]
 [ 8 32 82 49 42]]


ra---

### 5.2 역행렬 구하기

In [33]:
# np.linalg.inv(arr)
inverse_mat = np.linalg.inv(mat)
print(inverse_mat)

[[-0.00427984  0.00613047 -0.01996618  0.01528817  0.00726265]
 [ 0.01291851  0.00161705  0.03205763 -0.02034294 -0.02987502]
 [ 0.00681811  0.00441303  0.01119042 -0.01708649 -0.00451284]
 [ 0.00432808 -0.01300852 -0.01303073  0.01046279  0.01422173]
 [-0.02738845  0.00416094 -0.02726723  0.0337401   0.03740684]]


---

### 5.3 내적 구하기

In [38]:
dot_p = np.dot(mat, inverse_mat)
print(dot_p)

[[ 1.00000000e+00 -6.85215773e-17  6.59194921e-17 -6.93889390e-18
  -3.05311332e-16]
 [ 2.77555756e-16  1.00000000e+00  1.38777878e-17  1.38777878e-16
   1.11022302e-16]
 [-1.38777878e-17 -9.54097912e-18  1.00000000e+00  2.98372438e-16
  -4.16333634e-16]
 [-1.52655666e-16 -7.80625564e-18  1.83880688e-16  1.00000000e+00
  -3.60822483e-16]
 [-8.32667268e-17 -2.94902991e-17  2.01227923e-16 -2.08166817e-16
   1.00000000e+00]]


In [43]:
thread = 1e-10
dot_p[np.isclose(dot_p,0, atol=thread)] = 0
print(dot_p)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
np.isclose(dot_p, 0, atol=thread)

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])