In [ ]:
#KFold

import numpy as np
from sklearn.model_selection import KFold
X = ["a", "e","c","d"]
kf = KFold(n_splits=2)

for train, test in kf.split(X):
    print("%s%s"%(train,test)) #인덱스값만 나눠서 출력
    print(X[train[0]],X[train[1]],X[test[0]],X[test[1]])

[2 3][0 1]
c d a e
[0 1][2 3]
a e c d


In [1]:
#resample Bootstrap

import numpy as np
X=np.array([[1.,0.],[2.,1.],[0.,0.]])
y=np.array([0,1,2])
from scipy.sparse import coo_matrix
X_sparse = coo_matrix(X)
from sklearn.utils import resample

X,X_sparse, y = resample(X, X_sparse, y, random_state =0)

X # resample

array([[1., 0.],
       [2., 1.],
       [1., 0.]])

재표본추출방법

In [ ]:
# 데이터 관련 라이브러리
import numpy as np

# classification 관련 라이브러리
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# Resampling 관련 라이브러리
from sklearn.model_selection import KFold  # K-fold cross validation
from sklearn.utils import resample  # bootstrap

# 임의로 데이터를 섞기위한 라이브러리(random shuffling)
from sklearn.utils import shuffle

# 붓꽃(Iris) 데이터 로딩
from sklearn.datasets import load_iris

K-fold cross validation

In [ ]:
X=["a","b","c","d"]
kf = KFold(n_splits=2)
for train, test in kf.split(X):   # X를 나눠라 두번을 나누는데 서로세팅이 바뀜
    print("%s %s" %(train, test))
    print(X[train[0]], X[train[1]], X[test[0]], X[test[1]]) 

[2 3] [0 1]
c d a b
[0 1] [2 3]
a b c d


In [ ]:
kf.split(X)

<generator object _BaseKFold.split at 0x7f65e0f2ad50>

붓꽃 데이타예제(K-fold cross validation)

In [ ]:
X_iris, y_iris = load_iris(return_X_y = True)

In [ ]:
X_iris

In [ ]:
y_iris

In [ ]:
X_iris,y_iris = shuffle(X_iris, y_iris) #서플로 섞음

In [ ]:
# 5-fold cross-validation

kf = KFold(n_splits=5)
idx = 1
for train, val in kf.split(X_iris): #X_iris를 나눠라
    print("Fold: #",idx)

    ## K-Fold 결과확인
    print("%s %s" %(train, val)) #인덱스값만 리턴
    print(y_iris[train])
    print(y_iris[val])

    #LDA
    #training
    clf = LinearDiscriminantAnalysis().fit(X_iris[train], y_iris[train]) #Kfold로 나눈 train만 학습에 사용

    #클래스예측
    print("true label:", y_iris[val])
    print("pred label:", clf.predict(X_iris[val]))

    #accuracy
    print("accuracy:", clf.score(X_iris[val], y_iris[val])) #정확도평가

    print("---------------------------------------")
    idx+=1
                                           

간단한 예제(bootstrap)

In [ ]:
X = np.array([[1., 0.], [2., 1.], [0., 0.]])
y = np.array([0, 1, 2])
X, y = resample(X, y)
(X, y)

(array([[0., 0.],
        [0., 0.],
        [0., 0.]]), array([2, 2, 2]))

In [ ]:
X_iris, y_iris = load_iris(return_X_y=True)
X, y = resample(X_iris, y_iris)
y

array([1, 0, 2, 1, 1, 2, 1, 2, 2, 0, 2, 2, 0, 0, 2, 2, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 2, 0, 0, 2, 2, 0, 1, 2, 1, 0, 1, 0, 1, 1, 1, 2,
       0, 0, 1, 1, 2, 0, 0, 0, 2, 0, 1, 2, 0, 0, 0, 1, 0, 1, 1, 1, 0, 2,
       1, 0, 1, 0, 2, 2, 0, 0, 0, 1, 1, 1, 2, 1, 2, 2, 0, 1, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 0, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 2,
       1, 0, 1, 2, 1, 2, 0, 2, 1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 2, 2,
       1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 0, 2, 1, 2, 2, 2, 1, 0])

In [ ]:
# unique한 값 및 개수 출력
unique, counts = np.unique(y, return_counts=True)

In [ ]:
unique

array([0, 1, 2])

In [ ]:
counts

array([47, 43, 60])