In [1]:
# 데이터, 시각화 관련 라이브러리
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 선형회귀 관련 scikit-learn 라이브러리
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

# 선형회귀 관련 statsmodels 라이브러리
import statsmodels.api as sm

In [2]:
X = np.array([[0, 1], [1, 2], [2, 2.5]])
y = np.array([0, 1.2, 1.6])

reg = linear_model.LinearRegression()

reg.fit(X, y)

pred_train = reg.predict(X)

pred_test = reg.predict([[1.5, 2]])

In [3]:
pred_test

array([1.])

In [4]:
reg.coef_

array([-0.4,  1.6])

In [5]:
# 데이터 loading
# from google.colab import drive
# drive.mount('/content/drive')

ad = pd.read_csv("data/Advertising.csv", index_col=0)

In [6]:
ad

TV  Radio  Newspaper  Sales
1    230.1   37.8       69.2   22.1
2     44.5   39.3       45.1   10.4
3     17.2   45.9       69.3    9.3
4    151.5   41.3       58.5   18.5
5    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
196   38.2    3.7       13.8    7.6
197   94.2    4.9        8.1    9.7
198  177.0    9.3        6.4   12.8
199  283.6   42.0       66.2   25.5
200  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [7]:
# training/test data 분리
train = ad[:-20]
test = ad[-20:]

# training data의 feature와 response 분리
train_X = train[["TV", "Radio", "Newspaper"]]
train_y = train[["Sales"]]

# test data의 feature와 response 분리
test_X = test[["TV", "Radio", "Newspaper"]]
test_y = test[["Sales"]]

In [8]:
#선형회귀 object 생성

regr = linear_model.LinearRegression()

regr.fit(train_X[["TV", "Radio", "Newspaper"]], train_y)

train_y_pred = regr.predict(
    train_X[["TV", "Radio", "Newspaper"]])  #예측값을 넣을때는 X쪽 칼럼만 지정해서 넣어주면 y 예측값이 들어감

test_y_pred = regr.predict(test_X[["TV", "Radio", "Newspaper"]])

In [9]:
print(regr.coef_)
print(mean_squared_error(train_y, train_y_pred))
print(mean_squared_error(test_y, test_y_pred))
r2_score(train_y, train_y_pred)

[[ 0.04638909  0.18867512 -0.0024597 ]]
2.827418881491677
2.452817930717681


0.8923555807586847

5. Advertising data 선형회귀 statmodels

In [10]:
# statsmodels 사용을 위한 X0 feature 추가
# statsmodels의 OLS 함수는 데이터 내에 intercept에 해당하는 feature 필요
sm_train_X = train_X
sm_train_X["X0"] = 1

sm_test_X = test_X
sm_test_X["X0"] = 1

In [11]:
sm_train_X

TV  Radio  Newspaper  X0
1    230.1   37.8       69.2   1
2     44.5   39.3       45.1   1
3     17.2   45.9       69.3   1
4    151.5   41.3       58.5   1
5    180.8   10.8       58.4   1
..     ...    ...        ...  ..
176  276.9   48.9       41.8   1
177  248.4   30.2       20.3   1
178  170.2    7.8       35.2   1
179  276.7    2.3       23.7   1
180  165.6   10.0       17.6   1

[180 rows x 4 columns]

In [12]:
result = sm.OLS(train_y, sm_train_X[["X0", "TV", "Radio", "Newspaper"]]).fit()

result.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.892
Model:                            OLS   Adj. R-squared:                  0.891
Method:                 Least Squares   F-statistic:                     486.3
Date:                Sat, 16 Dec 2023   Prob (F-statistic):           6.57e-85
Time:                        02:13:39   Log-Likelihood:                -348.95
No. Observations:                 180   AIC:                             705.9
Df Residuals:                     176   BIC:                             718.7
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
X0             2.8399      0.342      8.293      0.000       2.164       3.516
TV             0.0464      0.001     31.154      0.000       0.043       0.049
Radio          0.1887      0.009     20.347      0.000       0.170       0.207
Newspaper     -0.0025      0.006     -0.395      0.693      -0.015       0.010
==============================================================================
Omnibus:                       56.196   Durbin-Watson:                   2.104
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              140.467
Skew:                          -1.343   Prob(JB):                     3.15e-31
Kurtosis:                       6.394   Cond. No.                         467.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
# <class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.892
Model:                            OLS   Adj. R-squared:                  0.891
Method:                 Least Squares   F-statistic:                     486.3
Date:                Tue, 12 Dec 2023   Prob (F-statistic):           6.57e-85
Time:                        02:13:14   Log-Likelihood:                -348.95
No. Observations:                 180   AIC:                             705.9
Df Residuals:                     176   BIC:                             718.7
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
X0             2.8399      0.342      8.293      0.000       2.164       3.516
TV             0.0464      0.001     31.154      0.000       0.043       0.049
Radio          0.1887      0.009     20.347      0.000       0.170       0.207
Newspaper     -0.0025      0.006     -0.395      0.693      -0.015       0.010
==============================================================================
Omnibus:                       56.196   Durbin-Watson:                   2.104
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              140.467
Skew:                          -1.343   Prob(JB):                     3.15e-31
Kurtosis:                       6.394   Cond. No.                         467.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

6. PolynomialFeatures() 예제

In [43]:
from sklearn.preprocessing import PolynomialFeatures

X = np.arange(6).reshape(3, 2)

In [44]:
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [56]:
#[1,a,b,a^2,ab,b^2] feature 생성
poly = PolynomialFeatures(3)
poly.fit_transform(X)

array([[  1.,   0.,   1.,   0.,   0.,   1.,   0.,   0.,   0.,   1.],
       [  1.,   2.,   3.,   4.,   6.,   9.,   8.,  12.,  18.,  27.],
       [  1.,   4.,   5.,  16.,  20.,  25.,  64.,  80., 100., 125.]])

In [57]:
#interaction feature만 생성
poly = PolynomialFeatures(interaction_only=True)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.],
       [ 1.,  2.,  3.,  6.],
       [ 1.,  4.,  5., 20.]])

Auto 데이터

In [58]:
# 데이터 loading
# from google.colab import drive
# 
# drive.mount('/content/drive')

auto = pd.read_csv("data/Auto.csv")
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           397 non-null    float64
 1   cylinders     397 non-null    int64  
 2   displacement  397 non-null    float64
 3   horsepower    397 non-null    object 
 4   weight        397 non-null    int64  
 5   acceleration  397 non-null    float64
 6   year          397 non-null    int64  
 7   origin        397 non-null    int64  
 8   name          397 non-null    object 
dtypes: float64(3), int64(4), object(2)
memory usage: 28.0+ KB


In [59]:
# horsepower의 ? 값을 0 으로 대체
auto["horsepower"] = auto["horsepower"].replace(to_replace="?", value=0)

# horserpower의 데이터 타입을 object에서 numeric으로 변경
auto["horsepower"] = pd.to_numeric(auto["horsepower"])

In [60]:
auto

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0    18.0          8         307.0         130    3504          12.0    70   
1    15.0          8         350.0         165    3693          11.5    70   
2    18.0          8         318.0         150    3436          11.0    70   
3    16.0          8         304.0         150    3433          12.0    70   
4    17.0          8         302.0         140    3449          10.5    70   
..    ...        ...           ...         ...     ...           ...   ...   
392  27.0          4         140.0          86    2790          15.6    82   
393  44.0          4          97.0          52    2130          24.6    82   
394  32.0          4         135.0          84    2295          11.6    82   
395  28.0          4         120.0          79    2625          18.6    82   
396  31.0          4         119.0          82    2720          19.4    82   

     origin                       name  
0         1  chevrolet chevelle malibu  
1         1          buick skylark 320  
2         1         plymouth satellite  
3         1              amc rebel sst  
4         1                ford torino  
..      ...                        ...  
392       1            ford mustang gl  
393       2                  vw pickup  
394       1              dodge rampage  
395       1                ford ranger  
396       1                 chevy s-10  

[397 rows x 9 columns]

Auto data 다중선형회귀(scikit-learn)

In [61]:
# horsepower의 다양한 feature 생성
auto["horsepower_2"] = auto["horsepower"] ** 2  # auto["새로운칼럼이름"] = auto["기존컬럼"]**승수
auto["horsepower_3"] = auto["horsepower"] ** 3
auto["horsepower_4"] = auto["horsepower"] ** 4
auto["horsepower_5"] = auto["horsepower"] ** 5

In [62]:
auto

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0    18.0          8         307.0         130    3504          12.0    70   
1    15.0          8         350.0         165    3693          11.5    70   
2    18.0          8         318.0         150    3436          11.0    70   
3    16.0          8         304.0         150    3433          12.0    70   
4    17.0          8         302.0         140    3449          10.5    70   
..    ...        ...           ...         ...     ...           ...   ...   
392  27.0          4         140.0          86    2790          15.6    82   
393  44.0          4          97.0          52    2130          24.6    82   
394  32.0          4         135.0          84    2295          11.6    82   
395  28.0          4         120.0          79    2625          18.6    82   
396  31.0          4         119.0          82    2720          19.4    82   

     origin                       name  horsepower_2  horsepower_3  \
0         1  chevrolet chevelle malibu         16900       2197000   
1         1          buick skylark 320         27225       4492125   
2         1         plymouth satellite         22500       3375000   
3         1              amc rebel sst         22500       3375000   
4         1                ford torino         19600       2744000   
..      ...                        ...           ...           ...   
392       1            ford mustang gl          7396        636056   
393       2                  vw pickup          2704        140608   
394       1              dodge rampage          7056        592704   
395       1                ford ranger          6241        493039   
396       1                 chevy s-10          6724        551368   

     horsepower_4  horsepower_5  
0       285610000   37129300000  
1       741200625  122298103125  
2       506250000   75937500000  
3       506250000   75937500000  
4       384160000   53782400000  
..            ...           ...  
392      54700816    4704270176  
393       7311616     380204032  
394      49787136    4182119424  
395      38950081    3077056399  
396      45212176    3707398432  

[397 rows x 13 columns]

In [64]:
# training/test data 분리
train = auto[:-40]
test = auto[-40:]

# training data의 feature와 response 분리
train_X = train[["horsepower", "horsepower_2", "horsepower_3", "horsepower_4", "horsepower_5"]]
train_y = train[["mpg"]]

# test data의 feature와 response 분리
test_X = test[["horsepower", "horsepower_2", "horsepower_3", "horsepower_4", "horsepower_5"]]
test_y = test[["mpg"]]

In [66]:
#선형회귀 object 생성
regr = linear_model.LinearRegression()

regr.fit(train_X[["horsepower"]], train_y)
#regr.fit(train_X[["horsepower", "horsepower_2"]], train_y)

train_y_pred = regr.predict(train_X[["horsepower"]])
# train_y_pred = regr.predict(train_X[["horsepower", "horsepower_2"]])

test_y_pred = regr.predict(test_X[["horsepower"]])
# test_y_pred = regr.predict(test_X[["horsepower", "horsepower_2"]])

In [67]:
print("Coefficient: \n", regr.coef_)
print("Traing MSE: %.3f" % mean_squared_error(train_y, train_y_pred))
print("Testing MSE: %.3f" % mean_squared_error(test_y, test_y_pred))
print("R^2:%.3f" % r2_score(train_y, train_y_pred))

Coefficient: 
 [[-0.14160083]]
Traing MSE: 24.027
Testing MSE: 43.997
R^2:0.587


In [68]:
regr = linear_model.LinearRegression()

#regr.fit(train_X[["horsepower"]], train_y)
regr.fit(train_X[["horsepower", "horsepower_2"]], train_y)

#train_y_pred = regr.predict(train_X[["horsepower"]])
train_y_pred = regr.predict(train_X[["horsepower", "horsepower_2"]])

#test_y_pred = regr.predict(test_X[["horsepower"]])
test_y_pred = regr.predict(test_X[["horsepower", "horsepower_2"]])

In [69]:
print("Coefficient: \n", regr.coef_)
print("Traing MSE: %.3f" % mean_squared_error(train_y, train_y_pred))
print("Testing MSE: %.3f" % mean_squared_error(test_y, test_y_pred))
print("R^2:%.3f" % r2_score(train_y, train_y_pred))

Coefficient: 
 [[-0.24477644  0.00043038]]
Traing MSE: 22.941
Testing MSE: 44.437
R^2:0.606
