**파이썬 1강 연습하기**

In [3]:
val = True
val = not val
print(val)

False


In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(
    {
        "Name": [
            "Braud, Mr. Owen Harris",
            "Allen, Mr. William Henry",
            "Bonnel, Miss. Ellizabeth",

        ],
        "Age":[22, 35, 58],
        "Sex":["male","male","Female"],
    }


)



In [ ]:
df

Name  Age     Sex
0    Braud, Mr. Owen Harris   22    male
1  Allen, Mr. William Henry   35    male
2  Bonnel, Miss. Ellizabeth   58  Female

In [ ]:
df["Age"].max()

58

In [ ]:
ages = pd.Series([20, 30, 40], name="Age")

In [ ]:
ages.max()

40

**numpy 시작하기**

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
data = np.array([[1,2],[3,4],[5,6]])

In [ ]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data[2,1]

6

In [ ]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [ ]:
data[0:2,0]

array([1, 3])

In [ ]:
b=np.zeros([2,3])

In [ ]:
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
data = np.array([1,2,3,4,5,6])

In [ ]:
data


array([1, 2, 3, 4, 5, 6])

In [ ]:
b=data.reshape(2,3)

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

**기본연산**

In [ ]:
data=np.array([[1,2],[3,4],[5,6]])
one_row = np.array([1,2])

In [ ]:
data + one_row

array([[2, 4],
       [4, 6],
       [6, 8]])

테이타 읽기/쓰기

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
csv_arr = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
np.savetxt('/content/drive/MyDrive/Colab Notebooks/data/new_file.csv', csv_arr)

In [ ]:
np.loadtxt('/content/drive/MyDrive/Colab Notebooks/data/new_file.csv')

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])