In [1]:
#Q1
import numpy as np

arr1 = np.random.rand(5, 3)
arr2 = np.random.rand(3, 2)

dot = np.dot(arr1, arr2)
print(dot, dot.shape)

[[0.36323383 0.26025336]
 [0.7787362  0.37453965]
 [0.62059818 0.42930575]
 [1.13143957 0.74720758]
 [0.84955681 0.42317267]] (5, 2)


In [2]:
#Q2
arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

concat_1 = np.vstack((arr1, arr2))  #axis 0
concat_2 = np.hstack((arr1, arr2))  #axis 1
print(concat_1, "\n", concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]] 
 [[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


In [3]:
#Q3
import numpy as np

xp = np.array([[1., 2., 3., 4., 5., 6.],
               [10., 20., 30., 40., 50., 60.]])

x_train = xp[0]
y_train = xp[1]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


In [4]:
#Q4

beta_gd = np.random.rand(1)
bias = np.random.rand(1)
print(beta_gd, bias)

[0.58722603] [0.52204041]


In [5]:
#Q5
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6],
               [3., 6., 9., 12., 15., 18.]])
x_train = [[i, 1.0] for i in xy[0]]  # x를 분리하고 인터셉트 추가
y_train = xy[1]

beta_gd = np.random.uniform(1, 5, 2)  # 그라디언트와 바이어스의 랜덤생성 정답[3, 0]
learning_rate = 0.01

for i in range(1000):
    error = y_train - x_train @ beta_gd  #  y-Xβ
    grad = - np.transpose(x_train) @ error  # X^T(y-Xβ)
    beta_gd = beta_gd - learning_rate * grad  #  β(t+1) = β(t)+ X^T(y-Xβ)

    if (i + 1) % 100 == 0 or i == 0:
        Error = sum(error ** 2)  # 에러를 제곱해서 더함.
        print(f'Epoch ({i + 1:10d}/1000) error:{Error:10f}, beta_gd: {beta_gd[0]:10f}. bias: {beta_gd[1]:10f}')

Epoch (         1/1000) error:367.623558, beta_gd:   2.571989. bias:   2.182205
Epoch (       100/1000) error:  0.625025, beta_gd:   2.830022. bias:   0.727710
Epoch (       200/1000) error:  0.069134, beta_gd:   2.943468. bias:   0.242023
Epoch (       300/1000) error:  0.007647, beta_gd:   2.981199. bias:   0.080493
Epoch (       400/1000) error:  0.000846, beta_gd:   2.993747. bias:   0.026770
Epoch (       500/1000) error:  0.000094, beta_gd:   2.997920. bias:   0.008903
Epoch (       600/1000) error:  0.000010, beta_gd:   2.999308. bias:   0.002961
Epoch (       700/1000) error:  0.000001, beta_gd:   2.999770. bias:   0.000985
Epoch (       800/1000) error:  0.000000, beta_gd:   2.999923. bias:   0.000328
Epoch (       900/1000) error:  0.000000, beta_gd:   2.999975. bias:   0.000109
Epoch (      1000/1000) error:  0.000000, beta_gd:   2.999992. bias:   0.000036
