In [1]:
#Q1
import numpy as np

arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)

dot = np.dot(arr1, arr2)
print(dot,dot.shape)

[[0.92991482 1.80491986]
 [0.37129588 1.04763278]
 [0.52816314 1.21710298]
 [0.09539552 0.29165306]
 [0.14796514 0.32780401]] (5, 2)


In [2]:
#Q2
arr1 = np.array([[5, 7],[9,11]], float)
arr2 = np.array([[2,4],[6,8]],float)

concat_1 = np.vstack((arr1, arr2)) #axis 0
concat_2 = np.hstack((arr1, arr2)) #axis 1
print(concat_1,"\n",concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]] 
 [[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


In [3]:
#Q3
import numpy as np

xp = np.array([[1.,2.,3.,4.,5.,6.],
               [10.,20.,30.,40.,50.,60.]])

x_train = xp[0]
y_train = xp[1]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


In [4]:
#Q4

beta_gd = np.random.rand(1)
bias = np.random.rand(1)
print(beta_gd, bias)

[0.28191496] [0.47151851]


In [5]:
#Q5
import numpy as np

xy = np.array([[1.,2.,3.,4.,5.,6],
               [3.,6., 9.,12.,15.,18.]])
x_train = [[i,1.0] for i in xy[0]]          # x를 분리하고 인터셉트 추가
y_train = xy[1]

beta_gd = np.random.uniform(1, 5, 2)        # 그라디언트와 바이어스의 랜덤생성 정답[3, 0]
learning_rate = 0.01

for i in range(1000):
    error = y_train - x_train @ beta_gd       #  y-Xβ
    grad = - np.transpose(x_train) @ error    # X^T(y-Xβ)
    beta_gd = beta_gd - learning_rate * grad  #  β(t+1) = β(t)+ X^T(y-Xβ)

    if (i+1)%100 == 0 or i == 0:
        Error = sum(error**2)                 # 에러를 제곱해서 더함.
        print(f'Epoch ({i+1:10d}/1000) error:{Error:10f}, beta_gd: {beta_gd[0]:10f}. bias: {beta_gd[1]:10f}')

Epoch (         1/1000) error: 76.399308, beta_gd:   2.684783. bias:   1.190622
Epoch (       100/1000) error:  0.191807, beta_gd:   2.905838. bias:   0.403127
Epoch (       200/1000) error:  0.021216, beta_gd:   2.968683. bias:   0.134073
Epoch (       300/1000) error:  0.002347, beta_gd:   2.989585. bias:   0.044590
Epoch (       400/1000) error:  0.000260, beta_gd:   2.996536. bias:   0.014830
Epoch (       500/1000) error:  0.000029, beta_gd:   2.998848. bias:   0.004932
Epoch (       600/1000) error:  0.000003, beta_gd:   2.999617. bias:   0.001640
Epoch (       700/1000) error:  0.000000, beta_gd:   2.999873. bias:   0.000546
Epoch (       800/1000) error:  0.000000, beta_gd:   2.999958. bias:   0.000181
Epoch (       900/1000) error:  0.000000, beta_gd:   2.999986. bias:   0.000060
Epoch (      1000/1000) error:  0.000000, beta_gd:   2.999995. bias:   0.000020
