In [9]:
import torch
import torch.nn as nn # 선형모델 hypothesis W,b 안씀 model.parameter를 대신씀
import torch.nn.functional as F # 코스트 펑크션 MSE등
import torch.optim as optim # 그라디언트 계산

In [10]:
torch.manual_seed(1)

In [11]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

In [12]:
print(x_train)
print(x_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


In [16]:
W = torch.zeros(1, requires_grad = True)
print(W)

tensor([0.], requires_grad=True)


In [17]:
b= torch.zeros(1, requires_grad = True)
print(b)


tensor([0.], requires_grad=True)


Hypothesis

In [19]:
hypothesis = x_train*W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


Cost

In [21]:
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [23]:
print(y_train)

tensor([[1.],
        [2.],
        [3.]])


In [25]:
print(hypothesis-y_train)

tensor([[-1.],
        [-2.],
        [-3.]], grad_fn=<SubBackward0>)


In [28]:
print((hypothesis-y_train)**2)

tensor([[1.],
        [4.],
        [9.]], grad_fn=<PowBackward0>)


In [31]:
cost = torch.mean((hypothesis-y_train)**2)
print(cost)

tensor(4.6667, grad_fn=<MeanBackward0>)


Gradient Descent

In [32]:
optimizer = optim.SGD([W,b], lr= 0.01)

In [33]:
optimizer.zero_grad()
cost.backward()
optimizer.step()


In [34]:
print(W)
print(b)

tensor([0.0933], requires_grad=True)
tensor([0.0400], requires_grad=True)


In [36]:
x_train = torch.FloatTensor([[1],[2],[3]])
y_train = torch.FloatTensor([[1],[2],[3]])

W = torch.zeros(1, requires_grad =True)
b = torch.zeros(1, requires_grad = True)

optimizer = optim.SGD([W,b], lr= 0.01)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    hypothesis = x_train * W + b
    cost = torch.mean((hypothesis-y_train)**2)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch %100 == 0:
        print(epoch,nb_epochs,W.item(), b.item(), cost.item())

0 1000 0.09333334118127823 0.03999999910593033 4.666666507720947
100 1000 0.8728456497192383 0.2890361249446869 0.012042650021612644
200 1000 0.90004962682724 0.22721074521541595 0.007441634312272072
300 1000 0.9214298725128174 0.17860840260982513 0.004598480183631182
400 1000 0.938236653804779 0.14040249586105347 0.0028415836859494448
500 1000 0.9514485597610474 0.11036901921033859 0.001755917095579207
600 1000 0.9618341326713562 0.0867600217461586 0.001085049589164555
700 1000 0.9699982404708862 0.06820125877857208 0.0006704938714392483
800 1000 0.976415753364563 0.05361240357160568 0.00041432344005443156
900 1000 0.9814606308937073 0.0421442985534668 0.0002560281427577138
1000 1000 0.9854263663291931 0.033129286020994186 0.0001582089316798374


In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

In [41]:
class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1,1) # 입력차원, 출력차원

    def forward(self,x):
        return self.linear(x) #hypthesis 계산

In [42]:
model = LinearRegressionModel()

In [43]:
hypothesis = model(x_train)

In [45]:
print(hypothesis)

tensor([[ 0.2755],
        [ 0.0816],
        [-0.1122]], grad_fn=<AddmmBackward0>)


In [47]:
print(y_train)

tensor([[1.],
        [2.],
        [3.]])


In [48]:
cost = F.mse_loss(hypothesis,y_train)

In [49]:
print(cost)

tensor(4.6303, grad_fn=<MseLossBackward0>)


In [50]:
optimizer.zero_grad()
cost.backward()
optimizer.step()

In [ ]:
_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])
# 모델 초기화
model = LinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=0.01)

nb_epochs = 1000
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    prediction = model(x_train) #hypothesis

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        params = list(model.parameters())
        W = params[0].item()
        b = params[1].item()
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W, b, cost.item()
        ))