In [1]:
import sympy as sym # 수학기호로 표현
from sympy.abc import x, y #x 항
import numpy as np

def func(val): #함수생성
    fun = sym.poly(x**2 + 2*x + 3)
    return fun

def func_gradient(fun, val): # 함수를 받아서 미분한뒤 인자를 넣어서 리턴
    function = fun(val)
    diff = sym.diff(function, x)
    return diff.subs(x,val)

def gradient_descent(fun, init_point, Ir_rate = 1e-2, epsilon = 1e-5):

    cnt = 0
    val = init_point
    diff= func_gradient(fun, init_point)   # 함수와 인자를 를 받아서 미분값

    while np.abs(diff) > epsilon:
        val = val - Ir_rate* diff # 미분값의 절대값을 점점 작아지는 방향으로 변수를 이동
        diff = func_gradient(fun, val) # 위의 변수일때 미분값
        cnt += 1

    print("함수: {}, 연산횟수: {}, 최소점:({},{})".format(fun(val), cnt, val, fun(val)))

gradient_descent(func, np.random.uniform(-2,2))

함수: Poly(x**2 + 2*x + 3, x, domain='ZZ'), 연산횟수: 508, 최소점:(-1.00000491928468,Poly(x**2 + 2*x + 3, x, domain='ZZ'))


In [2]:
import sympy as sym # 수학기호로 표현
from sympy.abc import x, y #x 항
import numpy as np

sym.diff(sym.poly(x**2 + 2*x*y + 3) + sym.cos(x + 2*y),x)


C:\Users\tomat\AppData\Local\Temp\ipykernel_15100\976591740.py:5: SymPyDeprecationWarning: 

Mixing Poly with non-polynomial expressions in binary
operations is deprecated. Either explicitly convert
the non-Poly operand to a Poly with as_poly() or
convert the Poly to an Expr with as_expr().

See https://docs.sympy.org/latest/explanation/active-deprecations.html#deprecated-poly-nonpoly-binary-operations
for details.

This has been deprecated since SymPy version 1.6. It
will be removed in a future version of SymPy.

  sym.diff(sym.poly(x**2 + 2*x*y + 3) + sym.cos(x + 2*y),x)


2*x + 2*y - sin(x + 2*y)

In [3]:
import sympy as sym # 수학기호로 표현
from sympy.abc import x, y #x 항
import numpy as np

def eval_(fun, val):
    val_x, val_y = val
    fun_eval = fun.subs(x, val_x).subs(y, val_y)
    return fun_eval

def func_multi(val):
    x_, y_ = val
    func = sym.poly( x**2 + 2*y**2)
    return eval_(func,[x_,y_]), func

def func_gradient(fun, val): # 함수를 받아서 미분한뒤 인자를 넣어서 리턴
    x_, y_ = val
    _, function = fun(val) #함수인자, 변수
    diff_x = sym.diff(function, x)
    diff_y = sym.diff(function, y)
    grad_vec = np.array([eval_(diff_x, [x_, y_]),eval_(diff_y, [x_, y_])], dtype= float)
    return grad_vec, [ diff_x, diff_y]

def gradient_descent(fun, init_point, Ir_rate = 1e-2, epsilon = 1e-5):

    cnt = 0
    val = init_point
    diff, _= func_gradient(fun, val)   # 함수와 인자를 를 받아서 미분값

    while np.linalg.norm(diff) > epsilon:
        val = val - Ir_rate* diff # 미분값의 절대값을 점점 작아지는 방향으로 변수를 이동
        diff,_ = func_gradient(fun, val) # 위의 변수일때 미분값
        cnt += 1

    print("함수: {}, 연산횟수: {}, 최소점:({},{})".format(fun(val), cnt, val, fun(val)[0]))

pt =[np.random.uniform(-2,2), np.random.uniform(-2,2)]

gradient_descent(func_multi, pt) #함수와 랜덤값을 받음

함수: (2.40634410962781e-11, Poly(x**2 + 2*y**2, x, y, domain='ZZ')), 연산횟수: 593, 최소점:([-4.90545014e-06  5.06993889e-11],2.40634410962781E-11)


In [4]:
import numpy as np

X = np.array([[1,1],[1,2],[2,2],[2,3]])
y = np.dot(X,np.array([1,2])) +3
print(y)

beta_gd = [10.1, 15.1, -6.5]
X_ = np.array([ np.append(x,[1]) for x in X])
print(X_)
for t in range(5000):
    error = y - X_ @beta_gd
    grad = - np.transpose(X_) @error
    beta_gd = beta_gd - 0.01 *grad

print(beta_gd)

[ 6  8  9 11]
[[1 1 1]
 [1 2 1]
 [2 2 1]
 [2 3 1]]
[1.00000367 1.99999949 2.99999516]


In [20]:
x = np.array([[1,1],[2,1],[3,1]])
y = np.array([4,8,12])

z = np.transpose(x) @ y
z

array([56, 24])