In [7]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [8]:
torch.manual_seed(1)

In [9]:
z = torch.rand(3,5, requires_grad= True)
hypothesis = F.softmax(z,dim= 1)
print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


In [10]:
y = torch.randint(5, (3,)).long() # 0~4의 범주에서 칼럼3개의 난수발생
print(y) #임의의 정답인덱스

tensor([0, 2, 1])


In [11]:
y_one_hot = torch.zeros_like(hypothesis) # z와 같은 onehot 벡터를 만들어줌
y_one_hot.scatter_(1,y.unsqueeze(1),1) # dim1에 대해서, y를 언스퀴즈한 인덱스 1을 뿌림 (3,)->(3,1)
#0,2,1번 인덱스에 1
#_ 함수는 in place로 교체되어 들어감

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [12]:
torch.log(F.softmax(z, dim=1))

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]], grad_fn=<LogBackward0>)

In [13]:
F.log_softmax(z, dim=1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward0>)

In [15]:
(y_one_hot* -torch.log(F.softmax(z, dim=1))).sum(dim=1).mean()

tensor(1.4689, grad_fn=<MeanBackward0>)

In [14]:
F.nll_loss(F.log_softmax(z, dim=1),y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

In [16]:
F.cross_entropy(z,y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

Data

In [17]:
xy = np.loadtxt('data/data-04-zoo.csv', delimiter=',', dtype=np.float32)


In [24]:
x_train = torch.FloatTensor(xy[:, 0:-1])
y_train = torch.FloatTensor(xy[:,[-1]]).squeeze() #[] 하나 더 넣은건 2차행렬로 변환 그후에 다시 1차행렬로 축소

In [25]:
print(x_train,y_train)

tensor([[1., 0., 0.,  ..., 0., 0., 1.],
        [1., 0., 0.,  ..., 1., 0., 1.],
        [0., 0., 1.,  ..., 1., 0., 0.],
        ...,
        [1., 0., 0.,  ..., 1., 0., 1.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 1., 1.,  ..., 1., 0., 0.]]) tensor([0., 0., 3., 0., 0., 0., 0., 3., 3., 0., 0., 1., 3., 6., 6., 6., 1., 0.,
        3., 0., 1., 1., 0., 1., 5., 4., 4., 0., 0., 0., 5., 0., 0., 1., 3., 0.,
        0., 1., 3., 5., 5., 1., 5., 1., 0., 0., 6., 0., 0., 0., 0., 5., 4., 6.,
        0., 0., 1., 1., 1., 1., 3., 3., 2., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        6., 3., 0., 0., 2., 6., 1., 1., 2., 6., 3., 1., 0., 6., 3., 1., 5., 4.,
        2., 2., 3., 0., 0., 1., 0., 5., 0., 6., 1.])


In [27]:
print(x_train.shape)
print(len(x_train))
print(x_train[:5])

torch.Size([101, 16])
101
tensor([[1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 4., 0., 0., 1.],
        [1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 0., 0., 4., 1., 0., 1.],
        [0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0.],
        [1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 4., 0., 0., 1.],
        [1., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 4., 1., 0., 1.]])
