In [1]:
import tensorflow as tf

tf.__version__

'2.10.0'

In [2]:
layers = tf.keras.layers

### RNN 테스트를 위한 데미데이터 생성

In [10]:
inputs = tf.random.normal([2, 5, 3])
print(inputs)

tf.Tensor(
[[[-0.68688816  0.63795984  0.4700734 ]
  [-0.5923181  -0.16772553 -0.01921861]
  [ 0.23098242 -0.6183914   1.1715894 ]
  [ 0.0895421  -0.6624265   0.03820596]
  [-1.1558853   1.6136357  -0.98270476]]

 [[ 1.6259651  -0.959666   -0.3704433 ]
  [ 1.8966867   0.1093685  -0.48551846]
  [ 0.8258324   1.2637748  -0.05963835]
  [-1.3298541  -0.00459423  2.1929214 ]
  [-0.62372756  0.33419794  0.74956524]]], shape=(2, 5, 3), dtype=float32)


* tf.keras를 이용한 다양한 RNN layer를 구현해보자

## Multi-Layer RNN

![multilayer_rnn](https://user-images.githubusercontent.com/11681225/46912330-5fe5fd00-cfad-11e8-95c2-94bb8e7b1bf6.png)

In [4]:
model = tf.keras.Sequential()

In [5]:
model.add(layers.SimpleRNN(10, return_sequences=True))
model.add(layers.SimpleRNN(10, return_sequences=True))
model.add(layers.SimpleRNN(10))

In [6]:
model(inputs)

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[ 0.72174615,  0.77355283, -0.41022566, -0.58233035,  0.2565149 ,
         0.22368903, -0.5222932 , -0.7762119 , -0.9794023 , -0.75570804],
       [-0.4479793 ,  0.45242217, -0.7894664 ,  0.30468154,  0.46541733,
         0.9425055 ,  0.9376879 ,  0.73485607,  0.6346286 ,  0.88124925]],
      dtype=float32)>

## Bi-directional RNN

![bidirectional_rnn](https://user-images.githubusercontent.com/11681225/46912324-3d53e400-cfad-11e8-8b09-85d8ebdb0e66.png)

In [7]:
model = tf.keras.Sequential()

In [8]:
model.add(layers.Bidirectional(layers.SimpleRNN(10, return_sequences=True)))
model.add(layers.Bidirectional(layers.SimpleRNN(10, return_sequences=True)))
model.add(layers.Bidirectional(layers.SimpleRNN(10)))

In [9]:
model(inputs)

<tf.Tensor: shape=(2, 20), dtype=float32, numpy=
array([[-0.39258775, -0.61516464, -0.35535762, -0.59894764,  0.13900165,
         0.4748278 , -0.13945699, -0.8799796 ,  0.9241901 ,  0.89523417,
        -0.20520902,  0.22513777, -0.21618927, -0.07128695, -0.03795622,
        -0.42836887, -0.56086934,  0.16964708, -0.46101588,  0.17506151],
       [ 0.93454796, -0.7735872 ,  0.2562902 , -0.653211  ,  0.33767   ,
         0.02525898,  0.01582919,  0.89980316, -0.812029  , -0.44537142,
         0.7528093 , -0.8198352 ,  0.8952355 , -0.4839596 , -0.5027139 ,
        -0.81105673,  0.7807631 ,  0.51459664,  0.8290246 ,  0.38515532]],
      dtype=float32)>