2023.09.17 프로그래머스 가입하고 5문제 풀어봄

In [1]:
# 최고의 조합 - 정답
def solution(n, s):
    if n > s:
        return  [-1]

    if s % n == 0:
        value = int(s / n)
        answer = [ value for i in range(n)]

    else:
        remain = s % n
        value = int(s // n)
        answer = [ value for i in range(n)]
        for i in range(len(answer)-1, len(answer)-remain-1, -1):
            answer[i] += 1

    return answer

In [2]:
solution(2,9)

[4, 5]

In [3]:
# 올바른괄호 - 정답

def solution(s):
    stack =[]
    for i in s:
        if( i == '('):
            stack.append(i)
        elif(i ==')'):
            if len(stack) == 0:
                return False
            elif stack[-1] == '(':
                stack.pop()
            else:
                return False
    if len(stack) ==0:
        return True
    else:
        return False

In [5]:
solution('()()')

True

In [6]:
#무인도 체류문제 - 정답

import numpy as np

def solution(input_map):

    map_number = np.array([[int(char) if char != 'X' else -1 for char in row] for row in input_map])
    if np.all(map_number == -1):
        return [-1]

    value_dict = {}
    mark = -2

    for i in range(len(map_number)):
        mark -= 1
        value_dict[mark] = 0
        for j in range(len(map_number[i])):
            if  map_number[i][j] != -1 :
                value_dict[mark] += int(map_number[i][j])
                map_number[i][j] = mark
            elif j != 0 and  j != len(map_number[i])-1 and map_number[i][j] == -1  and map_number[i][j+1] != -1:
                mark -=1
                value_dict[mark] = int(0)
                
    print(map_number)
    print(value_dict)
    mark = -1
    for i in range(len(map_number[0])):
        mark = -1
        for j in range(len(map_number)):
            if map_number[j][i] != -1:
                if (j == 0) or (j != 0 and map_number[j - 1][i] == -1):
                    mark = map_number[j][i]

                elif (j != 0)  and (map_number[j-1][i] !=- 1 ) and (map_number[j-1][i] != map_number[j][i]):
                    temp = map_number[j][i]
                    value_dict[mark] += int(value_dict[map_number[j][i]])
                    value_dict.pop(map_number[j][i])
                    map_number[map_number == temp] = mark
    print(map_number)
    print(value_dict)


    return (sorted([value for value in value_dict.values() if value != 0]))

In [7]:
solution(["X591X", "X1X5X", "X231X", "1XXX1"])

[[-1 -3 -3 -3 -1]
 [-1 -4 -1 -5 -1]
 [-1 -6 -6 -6 -1]
 [-7 -1 -1 -1 -8]]
{-3: 15, -4: 1, -5: 5, -6: 6, -7: 1, -8: 1}
[[-1 -3 -3 -3 -1]
 [-1 -3 -1 -3 -1]
 [-1 -3 -3 -3 -1]
 [-7 -1 -1 -1 -8]]
{-3: 27, -7: 1, -8: 1}


[1, 1, 27]

In [8]:
solution(["XXX","XXX","XXX"])

[-1]

In [9]:
# 소수만들기 - 정답

# import numpy as np
from itertools import combinations

def solution(array):
    
    def isprime(number):
        if number <2:
            return False
        for i in range(2, int(number**0.5)+1):
            if number%i == 0:
                return False
        return True
    
    # array = np.array(nums)
    
    combination = [list(i) for i in combinations(array,3)]

    summed_list = [sum(i) for i in combination]
    
    count = 0
    for i in range(len(summed_list)):
        if isprime(summed_list[i]):
            count +=1
    return count


In [10]:
solution([1,2,3,4,5])

2

In [11]:
# 사과상자담기 - 정답

import numpy as np

def solution(k, m, score):
    
    sorted_array = np.sort( np.array(score))[::-1]
    slice_lists = [ sorted_array[i:i+m].tolist() for i in range(0, len(sorted_array),m)]
    
    count = 0
    for i in slice_lists:
        if len(i) != m:
            break
        count +=  m * i[-1]
    
    return count
    

In [12]:
solution(4, 3 ,[4, 1, 2, 2, 4, 4, 4, 4, 1, 2, 4, 2])

33

In [13]:
solution(3,4,[1, 2, 3, 1, 2, 3, 1])

8

In [14]:
# 컨트롤제트 - 정답

def solution(s):
    number =[]
    number = s.split(' ') 
    count = 0
    temp = 0
    
    for i in number:
        try: 
            count += int(i)
            temp = int(i)
        except:
            if i == 'Z':
                count -= temp
    return count

solution("-1 -2 -3 Z")




-3

In [ ]:
from itertools import accumulate

def solution(cookie):
    answer = 0
    for m in range(len(cookie)-1):
        a = set(accumulate(reversed(cookie[:m+1])))
        b = set(accumulate(cookie[m+1:]))
        c = a & b

        if c:
            answer = max(*c, answer)
    return answer

In [17]:
a = [2, 3, -6, 1, 3, -1, 2, 4]

import numpy as np

def solution(sequence):
    
    sequence = np.array(sequence)
    length = len(sequence)
    
    pulse = [ 1 if i%2 ==0 else -1 for i in range(length)]
    array_1 = pulse * sequence
    
    cumulative_sum_1 = np.zeros(length+1)
    
    for i in range(length):
        cumulative_sum_1[i+1] = cumulative_sum_1[i]+ array_1[i]
    
    cumulative_sum_2 = -1 * cumulative_sum_1

    max_index_1 = np.argmax(cumulative_sum_1)
    max_cumalative_1 = max(cumulative_sum_1) - min(cumulative_sum_1[:max_index_1])
    max_index_2 = np.argmax(cumulative_sum_2)
    max_cumalative_2 = max(cumulative_sum_2) - min(cumulative_sum_2[:max_index_2])

    solution = int(max(max_cumalative_1,max_cumalative_2))
    return solution

solution(a)


10

In [19]:
import numpy as np

def solution(sequence):

    sequence = np.array(sequence)
    length = len(sequence)

    pulse = [1 if i % 2 == 0 else -1 for i in range(length)]
    array_1 = pulse * sequence

    cumulative_sum_1 = np.zeros(length + 1)

    for i in range(length):
        cumulative_sum_1[i + 1] = cumulative_sum_1[i] + array_1[i]

    cumulative_sum_2 = -1 * cumulative_sum_1

    max_index_1 = np.argmax(cumulative_sum_1)
    max_cumulative_1 = max(cumulative_sum_1) - min(cumulative_sum_1[:max_index_1]) if max_index_1 > 0 else cumulative_sum_1[0]

    max_index_2 = np.argmax(cumulative_sum_2)
    max_cumulative_2 = max(cumulative_sum_2) - min(cumulative_sum_2[:max_index_2]) if max_index_2 > 0 else cumulative_sum_2[0]

    solution = int(max(max_cumulative_1, max_cumulative_2))
    return solution

# 테스트
a = [2, 3, -6, 1, 3, -1, 2, 4]
print(solution(a))  # 출력: 10


10


In [17]:
import numpy as np
def solution(n, lighthouse):
    
    
    count ={}
    for i in lighthouse:
        if i[0] in count:
            count[i[0]].append(i[1])
        else:
            count[i[0]] = [i[1]]
        if i[1] in count:
            count[i[1]].append(i[0])
        else:
            count[i[1]] = [i[0]]
    print(count)
    
    
solution(10,[[4, 1], [5, 1], [5, 6], [7, 6], [1, 2], [1, 3], [6, 8], [2, 9], [9, 10]])


{4: [1], 1: [4, 5, 2, 3], 5: [1, 6], 6: [5, 7, 8], 7: [6], 2: [1, 9], 3: [1], 8: [6], 9: [2, 10], 10: [9]}
